ALTER TABLE "date_sheets" DROP COLUMN "overview";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "about_exam";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "exam_structure";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "preparation_tips";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "important_guidelines";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "general_instructions";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "exam_day_instructions";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "reporting_instructions";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "paper_pattern";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "marking_scheme";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "practical_exam_start";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "practical_exam_end";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "theory_exam_start";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "theory_exam_end";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "morning_time";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "evening_time";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "exam_duration";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "subjects";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "subject_groups";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "total_subjects";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "total_groups";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "supplementary_pdf";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "thumbnail_image";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "gallery_images";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "is_featured";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "is_urgent";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "is_revised";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "revised_date";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "download_count";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "share_count";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "tags";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "source";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "source_url";--> statement-breakpoint
ALTER TABLE "date_sheets" DROP COLUMN "related_date_sheets";