DROP TABLE "admission_offerings" CASCADE;--> statement-breakpoint
DROP TABLE "admissions" CASCADE;--> statement-breakpoint
DROP TABLE "blog_posts" CASCADE;--> statement-breakpoint
DROP TABLE "boards" CASCADE;--> statement-breakpoint
DROP TABLE "career_paths" CASCADE;--> statement-breakpoint
DROP TABLE "categories" CASCADE;--> statement-breakpoint
DROP TABLE "cities" CASCADE;--> statement-breakpoint
DROP TABLE "daily_stats" CASCADE;--> statement-breakpoint
DROP TABLE "date_sheets" CASCADE;--> statement-breakpoint
DROP TABLE "degrees" CASCADE;--> statement-breakpoint
DROP TABLE "institutes" CASCADE;--> statement-breakpoint
DROP TABLE "levels" CASCADE;--> statement-breakpoint
DROP TABLE "location_cache" CASCADE;--> statement-breakpoint
DROP TABLE "news" CASCADE;--> statement-breakpoint
DROP TABLE "page_views" CASCADE;--> statement-breakpoint
DROP TABLE "program_comparisons" CASCADE;--> statement-breakpoint
DROP TABLE "program_curriculum" CASCADE;--> statement-breakpoint
DROP TABLE "program_faqs" CASCADE;--> statement-breakpoint
DROP TABLE "program_offerings" CASCADE;--> statement-breakpoint
DROP TABLE "program_prerequisites" CASCADE;--> statement-breakpoint
DROP TABLE "program_reviews" CASCADE;--> statement-breakpoint
DROP TABLE "program_skills" CASCADE;--> statement-breakpoint
DROP TABLE "programs" CASCADE;--> statement-breakpoint
DROP TABLE "result_offerings" CASCADE;--> statement-breakpoint
DROP TABLE "results" CASCADE;--> statement-breakpoint
DROP TABLE "scholarships" CASCADE;--> statement-breakpoint
DROP TABLE "system_stats" CASCADE;--> statement-breakpoint
DROP TABLE "visitor_sessions" CASCADE;